# Generated by Django 3.2.12 on 2022-04-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0005_auto_20220410_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
